In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


%matplotlib inline

In [3]:
df = pd.read_csv('../data/alt_fuel.csv')

In [4]:
df.columns = [c.lower() for c in df.columns]
df.columns = df.columns.str.replace(' ', '_')

In [5]:
df.head()

,fuel_type_code,station_name,street_address,intersection_directions,city,state,zip,plus4,station_phone,status_code,...,ev_pricing_(french),lpg_nozzle_types,hydrogen_pressures,hydrogen_standards,cng_fill_type_code,cng_psi,cng_vehicle_class,lng_vehicle_class,ev_on-site_renewable_source,restricted_access
0,CNG,"Memphis Light, Gas and Water - North Center",1130 Tupelo St,NaN,Memphis,TN,38108,NaN,901-320-1062 901-320-1473,E,...,NaN,NaN,NaN,NaN,Q,3600.0,HD,NaN,NaN,NaN
1,LPG,Blossman Gas Inc,1121 Highway 19 E,"At Highway 37 E Bypass, 1 mile south of inters...",Elizabethton,TN,37643,NaN,423-542-3511,E,...,NaN,"[""ACME"", ""QUICK_CONNECT""]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LPG,Blossman Gas Inc,2798 APD 40,Off Highway 64,Cleveland,TN,37323,NaN,423-479-7569,E,...,NaN,"[""ACME"", ""QUICK_CONNECT""]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LPG,U-Haul,121 Moving Center Ct,Gallatin Rd,Madison,TN,37115,NaN,615-868-5081,E,...,NaN,"[""QUICK_CONNECT"", ""ACME""]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LPG,U-Haul,1420 NE Memorial Blvd,At Clark,Murfreesboro,TN,37129,NaN,615-896-9018,E,...,NaN,"[""QUICK_CONNECT"", ""ACME""]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_elec = df.loc[df['fuel_type_code'] == 'ELEC']

In [11]:
df_elec.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 688 entries, 40 to 871
Data columns (total 65 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   fuel_type_code                    688 non-null    object
 1   station_name                      688 non-null    object
 2   street_address                    687 non-null    object
 3   intersection_directions           41 non-null     object
 4   city                              688 non-null    object
 5   state                             688 non-null    object
 6   zip                               688 non-null    int64
 7   plus4                             0 non-null      float64
 8   station_phone                     626 non-null    object
 9   status_code                       688 non-null    object
 10  expected_date                     1 non-null      object
 11  groups_with_access_code           688 non-null    object
 12  access_days_time                  628 non-null    object
 13  cards_accepted                    14 non-null     object
 14  bd_blends                         0 non-null      object
 15  ng_fill_type_code                 0 non-null      object
 16  ng_psi                            0 non-null      float64
 17  ev_level1_evse_num                11 non-null     float64
 18  ev_level2_evse_num                629 non-null    float64
 19  ev_dc_fast_count                  71 non-null     float64
 20  ev_other_info                     0 non-null      float64
 21  ev_network                        688 non-null    object
 22  ev_network_web                    518 non-null    object
 23  geocode_status                    688 non-null    object
 24  latitude                          688 non-null    float64
 25  longitude                         688 non-null    float64
 26  date_last_confirmed               688 non-null    object
 27  id                                688 non-null    int64
 28  updated_at                        688 non-null    object
 29  owner_type_code                   242 non-null    object
 30  federal_agency_id                 40 non-null     float64
 31  federal_agency_name               40 non-null     object
 32  open_date                         688 non-null    object
 33  hydrogen_status_link              0 non-null      float64
 34  ng_vehicle_class                  0 non-null      object
 35  lpg_primary                       0 non-null      object
 36  e85_blender_pump                  0 non-null      object
 37  ev_connector_types                687 non-null    object
 38  country                           688 non-null    object
 39  intersection_directions_(french)  0 non-null      float64
 40  access_days_time_(french)         0 non-null      float64
 41  bd_blends_(french)                0 non-null      float64
 42  groups_with_access_code_(french)  688 non-null    object
 43  hydrogen_is_retail                0 non-null      float64
 44  access_code                       688 non-null    object
 45  access_detail_code                69 non-null     object
 46  federal_agency_code               40 non-null     object
 47  facility_type                     225 non-null    object
 48  cng_dispenser_num                 0 non-null      float64
 49  cng_on-site_renewable_source      0 non-null      object
 50  cng_total_compression_capacity    0 non-null      float64
 51  cng_storage_capacity              0 non-null      float64
 52  lng_on-site_renewable_source      0 non-null      object
 53  e85_other_ethanol_blends          0 non-null      object
 54  ev_pricing                        301 non-null    object
 55  ev_pricing_(french)               0 non-null      float64
 56  lpg_nozzle_types                  0 non-null      object
 57  hydrogen_pressures                0 non-null      float64
 58  hydrogen_standards                0 non-null      float64
 59  cng_fill_type_code                0 non-null      object
 60  cng_psi                           0 non-null      float64
 61  cng_vehicle_class                 0 non-null      object
 62  lng_vehicle_class                 0 non-null      object
 63  ev_on-site_renewable_source       10 non-null     object
 64  restricted_access                 0 non-null      float64
dtypes: float64(22), int64(2), object(41)
memory usage: 354.8+ KB

In [7]:
df_elec.head()

,fuel_type_code,station_name,street_address,intersection_directions,city,state,zip,plus4,station_phone,status_code,...,ev_pricing_(french),lpg_nozzle_types,hydrogen_pressures,hydrogen_standards,cng_fill_type_code,cng_psi,cng_vehicle_class,lng_vehicle_class,ev_on-site_renewable_source,restricted_access
40,ELEC,METRO NASHVILLE FULTON GARAGE 1,800 2nd Avenue South,NaN,Nashville,TN,37210,NaN,888-758-4389,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,ELEC,Oak Ridge Nissan,101 S Illinois Ave,NaN,Oak Ridge,TN,37830,NaN,865-482-5489,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,ELEC,Newton Nissan South,2801 Highway 231 N,NaN,Shelbyville,TN,37160,NaN,931-684-6811,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,ELEC,Mountain View Nissan,2100 S Market St,NaN,Chattanooga,TN,37408,NaN,423-756-1500,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,ELEC,Harold Mathews Nissan,185 Highway 76,NaN,Clarksville,TN,37043,NaN,931-552-7555,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN