In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


%matplotlib inline

In [5]:
df = pd.read_csv('../data/alt_fuel.csv')

In [6]:
df.columns = [c.lower() for c in df.columns] #postgres doesn't like capitals or spaces
df.columns = df.columns.str.replace(' ', '_')

In [7]:
df.head()

,fuel_type_code,station_name,street_address,intersection_directions,city,state,zip,plus4,station_phone,status_code,...,ev_pricing_(french),lpg_nozzle_types,hydrogen_pressures,hydrogen_standards,cng_fill_type_code,cng_psi,cng_vehicle_class,lng_vehicle_class,ev_on-site_renewable_source,restricted_access
0,CNG,"Memphis Light, Gas and Water - North Center",1130 Tupelo St,NaN,Memphis,TN,38108,NaN,901-320-1062 901-320-1473,E,...,NaN,NaN,NaN,NaN,Q,3600.0,HD,NaN,NaN,NaN
1,LPG,Blossman Gas Inc,1121 Highway 19 E,"At Highway 37 E Bypass, 1 mile south of inters...",Elizabethton,TN,37643,NaN,423-542-3511,E,...,NaN,"[""ACME"", ""QUICK_CONNECT""]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LPG,Blossman Gas Inc,2798 APD 40,Off Highway 64,Cleveland,TN,37323,NaN,423-479-7569,E,...,NaN,"[""ACME"", ""QUICK_CONNECT""]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LPG,U-Haul,121 Moving Center Ct,Gallatin Rd,Madison,TN,37115,NaN,615-868-5081,E,...,NaN,"[""QUICK_CONNECT"", ""ACME""]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LPG,U-Haul,1420 NE Memorial Blvd,At Clark,Murfreesboro,TN,37129,NaN,615-896-9018,E,...,NaN,"[""QUICK_CONNECT"", ""ACME""]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_elec = df.loc[df['fuel_type_code'] == 'ELEC']

In [9]:
df_elec.head()

,fuel_type_code,station_name,street_address,intersection_directions,city,state,zip,plus4,station_phone,status_code,...,ev_pricing_(french),lpg_nozzle_types,hydrogen_pressures,hydrogen_standards,cng_fill_type_code,cng_psi,cng_vehicle_class,lng_vehicle_class,ev_on-site_renewable_source,restricted_access
40,ELEC,METRO NASHVILLE FULTON GARAGE 1,800 2nd Avenue South,NaN,Nashville,TN,37210,NaN,888-758-4389,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,ELEC,Oak Ridge Nissan,101 S Illinois Ave,NaN,Oak Ridge,TN,37830,NaN,865-482-5489,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,ELEC,Newton Nissan South,2801 Highway 231 N,NaN,Shelbyville,TN,37160,NaN,931-684-6811,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,ELEC,Mountain View Nissan,2100 S Market St,NaN,Chattanooga,TN,37408,NaN,423-756-1500,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,ELEC,Harold Mathews Nissan,185 Highway 76,NaN,Clarksville,TN,37043,NaN,931-552-7555,E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN